### ISSUE TITLE
More information is needed about this project.

### ISSUE THREAD

**Issue by IgorA100** [mazer-dev/pejota#65]
It's great that new CRM projects are appearing, but...
- Not enough screenshots
- No demo site
- Not everyone will start a virtual machine and install the code in order to at least roughly understand what it is....

I hope this code will turn out to be an excellent project.
Good luck!

**Comment by nunomazer** [comment]
Thank you @IgorA100 .. I really know that, but this is a side project, and being an open source I hope people try it and contribute.
