### ISSUE TITLE
Contract management v1

### ISSUE THREAD

**Issue by nunomazer** [mazer-dev/pejota#8]
A client can have multiple contracts

## Table

- contract

fields:

- title
- content (rich text)
- start_at, required, date 
- end_at, nullable, date
- signatures, json: name, role, date (role is the participation type of the person, can use an ENUM in code: client, vendor, witness
- client_id
- project_id: nullable

## Relationship Manager

- Manage contracts from client page using relationship manager
- Manage contracts from project page using relationship manager

**Comment by nunomazer** [comment]
@GabrielDantasDs  this I think is a nice feature you could work on

**Comment by GabrielDantasDs** [comment]
Sure @nunomazer, i will be working on it
